artifacts_root : artifacts 

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/HarishKumarSedu/End_End_Ml_project_with_mlflow/raw/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
